# Extraction Profiles
profiles:
  standard:
    dpi: 300
    denoise: true
    binarize: false
    text_enhance: true
    min_text_length: 50
  
  low_res:
    dpi: 200
    denoise: true
    binarize: true
    contrast_boost: 2.0
    sharpening: 1.5
    min_text_length: 30
    text_reconstruction: true
    memory:
    max_image_cache: 2  # MB per image
    timeout: 120  # seconds per document

# Default Settings
default_profile: standard
max_workers: 8  # Optimal for most 8-core systems
chunk_size: 5   # Files per worker batch               

# Text extraction
text_extraction:
  min_text_length: 100
  dpi: 300
  poppler_path: "C:/Program Files/poppler/Library/bin"

# Text cleaning
text_cleaning:
  preserve_newlines: true
  fix_bullets: true
  normalize_dates: true

# Resource management
memory:
  max_pdf_size_mb: 50          # Reject files larger than this
  image_cache_size: 1024        # MB of RAM for image caching

resource_limits:
  max_file_size_mb: 50       # Skip files larger than this
  max_memory_per_worker: 512 # MB
  timeout_per_file: 300      # Seconds