paths:
  poppler_path: "C:\\Program Files\\poppler-25.04.0\\Library\\bin"
  tesseract_path: "C:\\Program Files\\Tesseract-OCR\\tesseract.exe"
  output_dir: "output"

ocr:
  default_engine: "tesseract"
  fallback_engine: "easyocr"
  languages: 
    - "eng"

logging:
  level: "INFO"
  file: "pdf_mining.log"