# Default configuration for PDF mining

# Input/Output settings
paths:
  input_dir: "data/input"
  output_dir: "data/output"
  temp_dir: "data/temp"

# PDF processing settings
pdf:
  extraction_mode: "text"  # Options: text, tables, both
  ocr_enabled: false
  page_range: "all"        # Options: "all" or specific range like "1-10"

# Text processing settings
text:
  remove_headers: true
  remove_footers: true
  clean_whitespace: true
  language: "en"

# Table extraction settings
tables:
  detect_borders: true
  min_row_count: 2
  parse_headers: true

# Output format settings
output:
  format: "json"           # Options: json, csv, txt
  save_images: false
  combine_pages: true

# Logging settings
logging:
  level: "INFO"
  save_logs: true
  log_file: "logs/mining.log"