# Tesseract/EasyOCR params
# This file contains the configuration for OCR processing using Tesseract and EasyOCR.
# It specifies the languages to be used, page segmentation mode, and OCR engine mode.

tesseract:
  languages: ["eng", "fra"]
  psm: 6          # Page segmentation mode
  oem: 1          # OCR engine mode
easyocr:
  gpu: false      # Disable GPU if unavailable

text_extraction:
  min_text_length: 50  # Minimum chars to consider extraction valid
  fallback_enabled: true
  fallback_threshold: 0.5  # Threshold for fallback to EasyOCR
  fallback_languages: ["en", "fr"]  # Languages for fallback OCR
  fallback_psm: 6  # Page segmentation mode for fallback