text_extraction:
  min_text_length: 50
  dpi: 300
  poppler_path: "C:/Program Files/poppler/Library/bin"  # REQUIRED
  thread_count: 2

ocr:
  engine: "hybrid"  # tesseract|easyocr|hybrid
  tesseract_config: "--psm 6"
  denoise: true
  binarize: false

layout:  # NEW SECTION
  model_path: "models/layout.model"
  threshold: 0.8
  min_region_size: 500  # Ignore small elements
  model_threshold: 0.7

table_detection:
  min_columns: 2          # Minimum columns to consider as table
  min_rows: 3             # Minimum rows to consider as table
  allowed_delimiters: ["|", ",", "\t"]
  max_column_variance: 2  # Allow ±2 columns difference