text_extraction:
  min_text_length: 50
  dpi: 300
  poppler_path: "C:/Program Files/poppler/Library/bin"  # REQUIRED
  thread_count: 2

ocr:
  engine: "hybrid"  # tesseract|easyocr|hybrid
  tesseract_config: "--psm 6"
  denoise: true
  binarize: false

layout:  # NEW SECTION
  model_path: "models/layout.model"
  threshold: 0.8